<?php
/*
SNK GPCL for PHP (General Purpose Class Library) version 2.2
(c) 2008-2017 SNK Software - www.snkey.net
All rights reserved.

de.inc
German language strings
*/

define("lc_login", "Login");
define("lc_password", "Kennwort");
define("lc_enter", "Eingeben");
define("lc_captcha", "CAPTCHA");
define("lc_errconect", "Kann die Verbindung zur DB: ");
define("lc_adenied", "Access wurde verweigert fur ");
define("lc_unlogged", "Nicht angemeldet oder Sie haben nicht genugend Rechte");

?>
