<?php
/*
SNK GPCL for PHP (General Purpose Class Library) version 2.2
(c) 2008-2017 SNK Software - www.snkey.net
All rights reserved.

en.inc
English language strings
*/

define("lc_login", "Login");
define("lc_password", "Password");
define("lc_enter", "Enter");
define("lc_captcha", "CAPTCHA");
define("lc_errconect", "Unable to connect to DB: ");
define("lc_adenied", "Access was denied for ");
define("lc_unlogged", "Not logged in or you do not have enough rigths");

?>
