<?php
/*
SNK GPCL for PHP (General Purpose Class Library) version 2.2
(c) 2008-2017 SNK Software - www.snkey.net
All rights reserved.

de.inc
Russian language strings. Please note about charset conversion (cc)
*/
include_once("procs.php");
define("lc_login",ncc("Логин"));
define("lc_password",ncc("Пароль"));
define("lc_enter",ncc("Войти"));
define("lc_captcha",ncc("Каптча"));
define("lc_errconect",ncc("Невозможно подключиться к БД "));
define("lc_adenied",ncc("Доступ запрещен для "));
define("lc_unlogged",ncc("Вход не выполнен или у вас нет прав на управление"));

?>
